version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: flight_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: flights_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flight_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/flights_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
